// Cada valor aqui precisa ser exatamente igual ao "code" cadastrado
// na tabela Permission (veja prisma/seed.ts) — é o que liga o token ao banco.
export enum Permissao {
  VISITOR_CREATE = 'VISITOR_CREATE',
  VISITOR_VIEW = 'VISITOR_VIEW',
  VISITOR_VIEW_SENSITIVE = 'VISITOR_VIEW_SENSITIVE',
  VISITOR_UPDATE = 'VISITOR_UPDATE',
  VISITOR_DELETE = 'VISITOR_DELETE',

  VISIT_CREATE = 'VISIT_CREATE',
  VISIT_CHECKOUT = 'VISIT_CHECKOUT',
  VISIT_VIEW = 'VISIT_VIEW',
  VISIT_UPDATE = 'VISIT_UPDATE',
  VISIT_DELETE = 'VISIT_DELETE',

  USER_CREATE = 'USER_CREATE',
  USER_LIST = 'USER_LIST',
  USER_UPDATE_OWN = 'USER_UPDATE_OWN',
  USER_CHANGE_ROLE = 'USER_CHANGE_ROLE',
  USER_DELETE = 'USER_DELETE',

  ROLE_PERMISSION_VIEW = 'ROLE_PERMISSION_VIEW',
  ROLE_PERMISSION_UPDATE = 'ROLE_PERMISSION_UPDATE',
}
